In [ ]:
df[c for c in df.columns if 'Time' in c]

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

* head() - It shows the first N rows in the data (by default, N=5).
* shape - It shows the total no. of rows and no. of columns of the dataframe
* index - This attribute provides the index of the dataframe
* columns - It shows the name of each column
* dtypes - It shows the data-type of each column
* unique() - In a column, it shows all the unique values. It can be applied on a single column only, not on the whole dataframe.
* nunique() - It shows the total no. of unique values in each column. It can be applied on a single column as well as on the whole dataframe.
* count - It shows the total no. of non-null values in each column. It can be applied on a single column as well as on the whole dataframe.
* value_counts - In a column, it shows all the unique values with their count. It can be applied on a single column only.
* info() - Provides basic information about the dataframe.

In [18]:
url = 'https://github.com/khala1391/DSL_Dataset/raw/main/project_1_Weather_Dataset.csv'
df = pd.read_csv( url , index_col='Date/Time', parse_dates=['Date/Time'])
df

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
Date/Time,,,,,,,
2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...
2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

# Subsetting

In [7]:
df['Temp_C']

Date/Time
2012-01-01 00:00:00   -1.8
2012-01-01 01:00:00   -1.8
2012-01-01 02:00:00   -1.8
2012-01-01 03:00:00   -1.5
2012-01-01 04:00:00   -1.5
                      ...
2012-12-31 19:00:00    0.1
2012-12-31 20:00:00    0.2
2012-12-31 21:00:00   -0.5
2012-12-31 22:00:00   -0.2
2012-12-31 23:00:00    0.0
Name: Temp_C, Length: 8784, dtype: float64

In [8]:
df[['Temp_C']]

                     Temp_C
Date/Time
2012-01-01 00:00:00    -1.8
2012-01-01 01:00:00    -1.8
2012-01-01 02:00:00    -1.8
2012-01-01 03:00:00    -1.5
2012-01-01 04:00:00    -1.5
...                     ...
2012-12-31 19:00:00     0.1
2012-12-31 20:00:00     0.2
2012-12-31 21:00:00    -0.5
2012-12-31 22:00:00    -0.2
2012-12-31 23:00:00     0.0

[8784 rows x 1 columns]

In [10]:
df['Temp_C']>1

Date/Time
2012-01-01 00:00:00    False
2012-01-01 01:00:00    False
2012-01-01 02:00:00    False
2012-01-01 03:00:00    False
2012-01-01 04:00:00    False
                       ...
2012-12-31 19:00:00    False
2012-12-31 20:00:00    False
2012-12-31 21:00:00    False
2012-12-31 22:00:00    False
2012-12-31 23:00:00    False
Name: Temp_C, Length: 8784, dtype: bool

In [11]:
df[df['Temp_C']>1]

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
Date/Time,,,,,,,
2012-01-01 15:00:00,1.8,-0.4,85,22,6.4,100.07,Fog
2012-01-01 16:00:00,2.6,-0.2,82,13,12.9,99.93,Mostly Cloudy
2012-01-01 17:00:00,3.0,0.0,81,13,16.1,99.81,Cloudy
2012-01-01 18:00:00,3.8,1.0,82,15,12.9,99.74,Rain
2012-01-01 19:00:00,3.1,1.3,88,15,12.9,99.68,Rain
...,...,...,...,...,...,...,...
2012-12-21 23:00:00,1.1,0.0,92,30,9.7,97.79,"Drizzle,Snow,Fog"
2012-12-22 00:00:00,1.1,-0.1,92,32,9.7,97.81,"Drizzle,Snow,Fog"
2012-12-22 01:00:00,1.2,0.1,92,30,12.9,97.84,Drizzle
2012-12-22 02:00:00,1.1,0.1,93,30,8.0,97.89,"Drizzle,Snow,Fog"
2012-12-22 03:00:00,1.1,0.1,93,28,9.7,97.93,"Drizzle,Snow,Fog"

In [14]:
(df['Temp_C']>1) & (df['Visibility_km']>30)

Date/Time
2012-01-01 00:00:00    False
2012-01-01 01:00:00    False
2012-01-01 02:00:00    False
2012-01-01 03:00:00    False
2012-01-01 04:00:00    False
                       ...
2012-12-31 19:00:00    False
2012-12-31 20:00:00    False
2012-12-31 21:00:00    False
2012-12-31 22:00:00    False
2012-12-31 23:00:00    False
Length: 8784, dtype: bool

In [15]:
df[(df['Temp_C']>1) & (df['Visibility_km']>30)]

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
Date/Time,,,,,,,
2012-01-23 11:00:00,1.2,-3.2,72,11,48.3,101.49,Cloudy
2012-01-23 12:00:00,2.3,-2.4,71,6,48.3,101.33,Cloudy
2012-01-23 13:00:00,2.5,-1.5,75,22,48.3,101.14,Cloudy
2012-01-23 14:00:00,2.7,-1.1,76,26,48.3,101.01,Rain
2012-01-28 14:00:00,1.2,-3.5,71,9,48.3,100.48,Cloudy
...,...,...,...,...,...,...,...
2012-12-07 14:00:00,3.9,-4.3,55,11,48.3,101.09,Cloudy
2012-12-07 15:00:00,3.9,-3.3,59,11,48.3,101.11,Cloudy
2012-12-14 07:00:00,2.0,-3.6,66,20,48.3,101.30,Mainly Clear
2012-12-14 08:00:00,1.5,-3.5,69,13,48.3,101.32,Mostly Cloudy
2012-12-14 09:00:00,2.3,-3.1,67,26,48.3,101.32,Mostly Cloudy

In [16]:
df.columns

Index(['Temp_C', 'Dew Point Temp_C', 'Rel Hum_%', 'Wind Speed_km/h',
       'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

In [19]:
df.columns[0:1]

Index(['Temp_C'], dtype='object')

In [20]:
df[df.columns[0:1]]

                     Temp_C
Date/Time
2012-01-01 00:00:00    -1.8
2012-01-01 01:00:00    -1.8
2012-01-01 02:00:00    -1.8
2012-01-01 03:00:00    -1.5
2012-01-01 04:00:00    -1.5
...                     ...
2012-12-31 19:00:00     0.1
2012-12-31 20:00:00     0.2
2012-12-31 21:00:00    -0.5
2012-12-31 22:00:00    -0.2
2012-12-31 23:00:00     0.0

[8784 rows x 1 columns]

In [24]:
df.columns[-1:]

Index(['Weather'], dtype='object')

In [26]:
df[df.columns[-1:]]

                                  Weather
Date/Time
2012-01-01 00:00:00                   Fog
2012-01-01 01:00:00                   Fog
2012-01-01 02:00:00  Freezing Drizzle,Fog
2012-01-01 03:00:00  Freezing Drizzle,Fog
2012-01-01 04:00:00                   Fog
...                                   ...
2012-12-31 19:00:00                  Snow
2012-12-31 20:00:00                  Snow
2012-12-31 21:00:00                  Snow
2012-12-31 22:00:00                  Snow
2012-12-31 23:00:00                  Snow

[8784 rows x 1 columns]

In [27]:
df.columns[-1]

'Weather'

In [28]:
type(df.columns[-1])

str

In [29]:
df[df.columns[-1]]

Date/Time
2012-01-01 00:00:00                     Fog
2012-01-01 01:00:00                     Fog
2012-01-01 02:00:00    Freezing Drizzle,Fog
2012-01-01 03:00:00    Freezing Drizzle,Fog
2012-01-01 04:00:00                     Fog
                               ...
2012-12-31 19:00:00                    Snow
2012-12-31 20:00:00                    Snow
2012-12-31 21:00:00                    Snow
2012-12-31 22:00:00                    Snow
2012-12-31 23:00:00                    Snow
Name: Weather, Length: 8784, dtype: object

In [30]:
type(df[df.columns[-1]])

pandas.core.series.Series

In [31]:
df[[df.columns[-1]]]

                                  Weather
Date/Time
2012-01-01 00:00:00                   Fog
2012-01-01 01:00:00                   Fog
2012-01-01 02:00:00  Freezing Drizzle,Fog
2012-01-01 03:00:00  Freezing Drizzle,Fog
2012-01-01 04:00:00                   Fog
...                                   ...
2012-12-31 19:00:00                  Snow
2012-12-31 20:00:00                  Snow
2012-12-31 21:00:00                  Snow
2012-12-31 22:00:00                  Snow
2012-12-31 23:00:00                  Snow

[8784 rows x 1 columns]

In [32]:
df.head()

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
Date/Time,,,,,,,
2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog

# GroupBy

In [33]:
df.groupby(by='Weather').mean()

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather,,,,,,
Clear,6.825716,0.089367,64.497738,10.557315,30.153243,101.587443
Cloudy,7.970544,2.375810,69.592593,16.127315,26.625752,100.911441
Drizzle,7.353659,5.504878,88.243902,16.097561,17.931707,100.435366
"Drizzle,Fog",8.067500,7.033750,93.275000,11.862500,5.257500,100.786625
"Drizzle,Ice Pellets,Fog",0.400000,-0.700000,92.000000,20.000000,4.000000,100.790000
"Drizzle,Snow",1.050000,0.150000,93.500000,14.000000,10.500000,100.890000
"Drizzle,Snow,Fog",0.693333,0.120000,95.866667,15.533333,5.513333,99.281333
Fog,4.303333,3.159333,92.286667,7.946667,6.248000,101.184067
Freezing Drizzle,-5.657143,-8.000000,83.571429,16.571429,9.200000,100.202857
"Freezing Drizzle,Fog",-2.533333,-4.183333,88.500000,17.000000,5.266667,100.441667
"Freezing Drizzle,Haze",-5.433333,-8.000000,82.000000,10.333333,2.666667,100.316667
"Freezing Drizzle,Snow",-5.109091,-7.072727,86.090909,16.272727,5.872727,100.520909
Freezing Fog,-7.575000,-9.250000,87.750000,4.750000,0.650000,102.320000
Freezing Rain,-3.885714,-6.078571,84.642857,19.214286,8.242857,99.647143
"Freezing Rain,Fog",-2.225000,-3.750000,89.500000,15.500000,7.550000,99.945000
"Freezing Rain,Haze",-4.900000,-7.450000,82.500000,7.500000,2.400000,100.375000
"Freezing Rain,Ice Pellets,Fog",-2.600000,-3.700000,92.000000,28.000000,8.000000,100.950000
"Freezing Rain,Snow Grains",-5.000000,-7.300000,84.000000,32.000000,4.800000,98.560000
Haze,-0.200000,-2.975000,81.625000,10.437500,7.831250,101.482500
Mainly Clear,12.558927,4.581671,60.667142,14.144824,34.264862,101.248832
"Moderate Rain,Fog",1.700000,0.800000,94.000000,17.000000,6.400000,99.980000
Moderate Snow,-5.525000,-7.250000,87.750000,33.750000,0.750000,100.275000
"Moderate Snow,Blowing Snow",-5.450000,-6.500000,92.500000,40.000000,0.600000,100.570000
Mostly Cloudy,10.574287,3.131174,62.102465,15.813920,31.253842,101.025288
Rain,9.786275,7.042810,83.624183,19.254902,18.856536,100.233333
Rain Showers,13.722340,9.187766,75.159574,17.132979,22.816489,100.404043
"Rain Showers,Fog",12.800000,12.100000,96.000000,13.000000,6.400000,99.830000
"Rain Showers,Snow Showers",2.150000,-1.500000,76.500000,22.500000,21.700000,101.100000
"Rain,Fog",8.273276,7.219828,93.189655,14.793103,6.873276,100.500862
"Rain,Haze",4.633333,2.066667,83.333333,11.666667,6.700000,100.540000
"Rain,Ice Pellets",0.600000,-0.600000,92.000000,24.000000,9.700000,100.120000
"Rain,Snow",1.055556,-0.566667,89.000000,28.388889,11.672222,99.951111
"Rain,Snow Grains",1.900000,-2.100000,75.000000,26.000000,25.000000,100.600000
"Rain,Snow,Fog",0.800000,0.300000,96.000000,9.000000,6.400000,100.730000
"Rain,Snow,Ice Pellets",1.100000,-0.175000,91.500000,23.250000,6.000000,100.105000
Snow,-4.524103,-7.623333,79.307692,20.038462,11.171795,100.536103
Snow Pellets,0.700000,-6.400000,59.000000,35.000000,2.400000,99.700000
Snow Showers,-3.506667,-7.866667,72.350000,19.233333,20.158333,100.963500
"Snow Showers,Fog",-10.675000,-11.900000,90.750000,13.750000,7.025000,101.292500
"Snow,Blowing Snow",-5.410526,-7.621053,84.473684,34.842105,4.105263,99.704737
"Snow,Fog",-5.075676,-6.364865,90.675676,17.324324,4.537838,100.688649
"Snow,Haze",-4.020000,-6.860000,80.600000,5.000000,4.640000,100.782000
"Snow,Ice Pellets",-1.883333,-3.666667,87.666667,23.833333,7.416667,100.548333
Thunderstorms,24.150000,19.750000,77.000000,7.500000,24.550000,100.230000
"Thunderstorms,Heavy Rain Showers",10.900000,9.000000,88.000000,9.000000,2.400000,100.260000
"Thunderstorms,Moderate Rain Showers,Fog",19.600000,18.500000,93.000000,15.000000,3.200000,100.010000
"Thunderstorms,Rain",20.433333,18.533333,89.000000,15.666667,19.833333,100.420000
"Thunderstorms,Rain Showers",20.037500,17.618750,86.375000,18.312500,15.893750,100.233750
"Thunderstorms,Rain Showers,Fog",21.600000,18.700000,84.000000,19.666667,9.700000,100.063333
"Thunderstorms,Rain,Fog",20.600000,18.600000,88.000000,19.000000,4.800000,100.080000